### ISSUE TITLE
list Index out of range

### ISSUE THREAD

**Issue by amleshkumar** [jblasch/ECE428___KL_Tool#1]
Hi,
I am learning K-L Algorithm programming using python & I found your github code.
Could you help to solve the following issue?

def new_node_lists(nListA, nListB, hgSet):
    nAPrime = []
    nBPrime = []
      
    a2bSwap = hgSet[0][0]
    b2aSwap = hgSet[0][1] 
        
hgSet shows error while running on python 3.6. 
error: hgSet list Index out of range.
could you please help to solve this issue?

Thank you
Amlesh Kumar

**Comment by amleshkumar** [comment]
![index out of range](https://user-images.githubusercontent.com/34007047/70814062-ad563800-1e05-11ea-9a67-f6fd8fdf85c1.PNG)

I also attached screenshot of error.

**Comment by jblasch** [comment]
Hi Amlesh,

I am not a Python expert, but I wrote my program using Python 2, so I imagine there would be syntax incompatibilities trying to run it in Python 3.

**Comment by amleshkumar** [comment]
ok. Thank you for your response.
